echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.........................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling..........................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling...........................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling............................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.............................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling..............................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling...............................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling..................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling...................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling....................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.....................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling......................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.......................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling........................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.........................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling..........................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling...........................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling............................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.............................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling..............................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling...............................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling..................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling...................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling....................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.....................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling......................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.......................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling........................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.........................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling..........................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling...........................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling............................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.............................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling..............................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling...............................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling................................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.................................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling..................................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling...................................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling....................................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.....................................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling......................................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.......................................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling........................................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.........................................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling..........................................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling...........................................................................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling............................................................................
echo....o instaling.
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling..
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling...
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling....
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling..................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling...................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling....................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.....................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling......................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.......................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling........................
echo instaling.....
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling......
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.......
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling........
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.........
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling..........
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling...........
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling............
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.............
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling..............
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling...............
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling................
echo Please wait.
echo Please wait..
echo Please wait...
echo Please wait....
echo instaling.................
echo Please wait.
@echo off
cls
cd ../ && mkdir [mod_resurce] && cd [mod_resurce] && git clone https://github.com/HACKERA316/gta5mods.git
cls
echo installation complete please press "space"

pause
